PROJECT_NAME="RFID"
SERVICE_NAME="RFID.service"

ROOT_FRONTEND=/var/www/automacao.tce.go.gov.br/$PROJECT_NAME

ROOT_SOFTWARES=/var/softwaresTCE
ROOT_BACKEND=$ROOT_SOFTWARES"/"$PROJECT_NAME

GIT_REPO_NAME="RFID"
GIT_REPO_OWNER="TCE-Manutencao-Predial"
GIT_REPO_LINK="https://github.com/$GIT_REPO_OWNER/$GIT_REPO_NAME.git"

APACHE_CONFIG_DIR="/etc/httpd/conf.d"
APACHE_CONFIG_FILE="RFID.conf"

HTACCESS_FILE="scripts/htaccess"

# Configurações 
AUTO_HABILITAR_SERVICO=true
